namespace Filament.SourceGen;

using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

/// <summary>
/// Emits, for every <c>[Scriptable]</c> record/struct, a converter with
/// <c>ToLua</c> (→ a plain snake_case Lua table) and <c>FromLua</c> (→ a
/// <c>Result&lt;T,LuaError&gt;</c>, never a throw). A <c>[ModuleInitializer]</c>
/// self-registers every converter into the runtime registry so they resolve
/// across assembly boundaries.
/// </summary>
[Generator]
public sealed class ScriptableConverterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var models = context.SyntaxProvider.ForAttributeWithMetadataName(
            TypeAnalysis.ScriptableAttr,
            predicate: static (node, _) => node is TypeDeclarationSyntax,
            transform: static (ctx, _) => Build((INamedTypeSymbol)ctx.TargetSymbol))
            .Where(static m => m is { Valid: true })
            .Collect();

        context.RegisterSourceOutput(models, static (spc, items) =>
        {
            if (items.IsDefaultOrEmpty) return;
            spc.AddSource("ScriptableConverters.g.cs", SourceText.From(Emit(items!), Encoding.UTF8));
        });
    }

    private static Model? Build(INamedTypeSymbol type)
    {
        var ctor = TypeAnalysis.PrimaryConstructor(type);
        if (ctor is null) return new Model(string.Empty, string.Empty, false, ImmutableArray<Field>.Empty);

        var fqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var fields = ImmutableArray.CreateBuilder<Field>();
        foreach (var p in ctor.Parameters)
        {
            var shape = TypeAnalysis.Classify(p.Type);
            if (!shape.IsSupported)
                return new Model(fqn, type.Name, false, ImmutableArray<Field>.Empty); // analyzer reports FILA0002
            fields.Add(new Field(
                p.Name,
                p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                TypeAnalysis.ResolveKey(type, p),
                shape.Wrap, shape.Scalar,
                shape.Inner.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
        }

        var safe = SafeName(fqn);
        return new Model(fqn, type.Name, true, fields.ToImmutable()) { Safe = safe };
    }

    private static string SafeName(string fqn)
    {
        var sb = new StringBuilder(fqn.Length);
        foreach (var c in fqn) sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        return sb.ToString();
    }

    private static string Emit(ImmutableArray<Model> models)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Filament");
        sb.AppendLine("{");
        sb.AppendLine("    using global::MoonSharp.Interpreter;");
        sb.AppendLine("    internal static class GeneratedScriptableConverters");
        sb.AppendLine("    {");

        // Module initializer: register every converter at assembly load.
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void __RegisterAll()");
        sb.AppendLine("        {");
        foreach (var m in models)
            sb.AppendLine($"            global::Filament.ScriptableMarshal.Register(new {m.Safe}Converter());");
        sb.AppendLine("        }");
        sb.AppendLine();

        foreach (var m in models)
            EmitType(sb, m);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitType(StringBuilder sb, Model m)
    {
        // Converter class.
        sb.AppendLine($"        private sealed class {m.Safe}Converter : global::Filament.IScriptableConverter<{m.Fqn}>");
        sb.AppendLine("        {");
        sb.AppendLine($"            public Table ToLua({m.Fqn} value, Script script) => __ToLua_{m.Safe}(value, script);");
        sb.AppendLine($"            public global::Filament.Result<{m.Fqn}, global::Filament.LuaError> FromLua(DynValue v) => __FromLua_{m.Safe}(v);");
        sb.AppendLine("        }");
        sb.AppendLine();

        // ToLua.
        sb.AppendLine($"        internal static Table __ToLua_{m.Safe}({m.Fqn} value, Script script)");
        sb.AppendLine("        {");
        sb.AppendLine("            var t = new Table(script);");
        foreach (var f in m.Fields) EmitToLuaField(sb, f);
        sb.AppendLine("            return t;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // FromLua.
        sb.AppendLine($"        internal static global::Filament.Result<{m.Fqn}, global::Filament.LuaError> __FromLua_{m.Safe}(DynValue __v)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (__v.Type != DataType.Table)");
        sb.AppendLine($"                return global::Filament.Result.Err(global::Filament.LuaError.TypeMismatch(\"{m.TypeName}\", __v.Type.ToString()));");
        sb.AppendLine("            var __t = __v.Table;");
        foreach (var f in m.Fields) EmitFromLuaField(sb, f, m.TypeName);
        var args = string.Join(", ", m.Fields.Select(f => "__" + f.Param));
        sb.AppendLine($"            return global::Filament.Result.Ok(new {m.Fqn}({args}));");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitToLuaField(StringBuilder sb, Field f)
    {
        var read = "value." + f.Param;
        switch (f.Wrap)
        {
            case TypeAnalysis.Wrap.None:
                sb.AppendLine($"            t.Set(\"{f.Key}\", {PushExpr(f.Scalar, read, f.Inner)});");
                break;
            case TypeAnalysis.Wrap.Option:
                sb.AppendLine($"            if ({read}.TryGet(out var __o_{f.Param})) t.Set(\"{f.Key}\", {PushExpr(f.Scalar, "__o_" + f.Param, f.Inner)});");
                break;
            case TypeAnalysis.Wrap.List:
                sb.AppendLine("            {");
                sb.AppendLine($"                var __l = new Table(script); var __src = {read};");
                sb.AppendLine($"                for (int __i = 0; __i < __src.Count; __i++) __l.Set(__i + 1, {PushExpr(f.Scalar, "__src[__i]", f.Inner)});");
                sb.AppendLine($"                t.Set(\"{f.Key}\", DynValue.NewTable(__l));");
                sb.AppendLine("            }");
                break;
        }
    }

    /// <summary>C# expression turning a value into a DynValue for the given scalar.</summary>
    private static string PushExpr(TypeAnalysis.Scalar scalar, string expr, string innerFqn) => scalar switch
    {
        TypeAnalysis.Scalar.Bool => $"DynValue.NewBoolean({expr})",
        TypeAnalysis.Scalar.Int => $"DynValue.NewNumber({expr})",
        TypeAnalysis.Scalar.Long => $"DynValue.NewNumber({expr})",
        TypeAnalysis.Scalar.Float => $"DynValue.NewNumber({expr})",
        TypeAnalysis.Scalar.Double => $"DynValue.NewNumber({expr})",
        TypeAnalysis.Scalar.String => $"DynValue.NewString({expr})",
        TypeAnalysis.Scalar.Enum => $"DynValue.NewString({expr}.ToString())",
        TypeAnalysis.Scalar.Scriptable => $"DynValue.NewTable(global::Filament.ScriptableMarshal.ToLua<{innerFqn}>({expr}, script))",
        _ => "DynValue.Nil",
    };

    private static void EmitFromLuaField(StringBuilder sb, Field f, string typeName)
    {
        var p = f.Param;
        sb.AppendLine($"            var __{p}_dv = __t.Get(\"{f.Key}\");");
        switch (f.Wrap)
        {
            case TypeAnalysis.Wrap.None:
                sb.AppendLine($"            if (global::Filament.ScriptableMarshal.IsAbsent(__{p}_dv)) return global::Filament.Result.Err(global::Filament.LuaError.MissingRequiredField(\"{typeName}\", \"{f.Key}\"));");
                sb.AppendLine($"            var __{p}_r = {ReadExpr(f, "__" + p + "_dv", typeName)};");
                sb.AppendLine($"            if (__{p}_r.TryGetError(out var __{p}_e)) return global::Filament.Result.Err(__{p}_e);");
                sb.AppendLine($"            __{p}_r.TryGet(out var __{p});");
                break;
            case TypeAnalysis.Wrap.Option:
                sb.AppendLine($"            {f.ClrTypeFqn} __{p};");
                sb.AppendLine($"            if (global::Filament.ScriptableMarshal.IsAbsent(__{p}_dv)) {{ __{p} = global::Filament.Option.None; }}");
                sb.AppendLine("            else {");
                sb.AppendLine($"                var __{p}_r = {ReadExpr(f, "__" + p + "_dv", typeName)};");
                sb.AppendLine($"                if (__{p}_r.TryGetError(out var __{p}_e)) return global::Filament.Result.Err(__{p}_e);");
                sb.AppendLine($"                __{p}_r.TryGet(out var __{p}_v); __{p} = global::Filament.Option.Some(__{p}_v);");
                sb.AppendLine("            }");
                break;
            case TypeAnalysis.Wrap.List:
                sb.AppendLine($"            if (global::Filament.ScriptableMarshal.IsAbsent(__{p}_dv)) return global::Filament.Result.Err(global::Filament.LuaError.MissingRequiredField(\"{typeName}\", \"{f.Key}\"));");
                sb.AppendLine($"            var __{p}_r = global::Filament.ScriptableMarshal.AsList<{f.Inner}>(__{p}_dv, \"{typeName}\", \"{f.Key}\", static __e => {ElementReadExpr(f, "__e", typeName)});");
                sb.AppendLine($"            if (__{p}_r.TryGetError(out var __{p}_e)) return global::Filament.Result.Err(__{p}_e);");
                sb.AppendLine($"            __{p}_r.TryGet(out var __{p});");
                break;
        }
    }

    /// <summary>Read a single scalar from a DynValue var → Result&lt;inner,LuaError&gt;.</summary>
    private static string ReadExpr(Field f, string dv, string typeName) => f.Scalar switch
    {
        TypeAnalysis.Scalar.Bool => $"global::Filament.ScriptableMarshal.AsBool({dv}, \"{typeName}\", \"{f.Key}\")",
        TypeAnalysis.Scalar.Int => $"global::Filament.ScriptableMarshal.AsInt({dv}, \"{typeName}\", \"{f.Key}\")",
        TypeAnalysis.Scalar.Long => $"global::Filament.ScriptableMarshal.AsLong({dv}, \"{typeName}\", \"{f.Key}\")",
        TypeAnalysis.Scalar.Float => $"global::Filament.ScriptableMarshal.AsFloat({dv}, \"{typeName}\", \"{f.Key}\")",
        TypeAnalysis.Scalar.Double => $"global::Filament.ScriptableMarshal.AsDouble({dv}, \"{typeName}\", \"{f.Key}\")",
        TypeAnalysis.Scalar.String => $"global::Filament.ScriptableMarshal.AsString({dv}, \"{typeName}\", \"{f.Key}\")",
        TypeAnalysis.Scalar.Enum => $"global::Filament.ScriptableMarshal.AsEnum<{f.Inner}>({dv}, \"{typeName}\", \"{f.Key}\")",
        TypeAnalysis.Scalar.Scriptable => $"global::Filament.ScriptableMarshal.AsScriptable<{f.Inner}>({dv}, \"{typeName}\", \"{f.Key}\")",
        _ => $"global::Filament.Result.Err(global::Filament.LuaError.FieldCoercion(\"{typeName}\", \"{f.Key}\", \"unsupported\"))",
    };

    // For list elements the scalar is the element type (same as ReadExpr but on the element DynValue).
    private static string ElementReadExpr(Field f, string dv, string typeName) => ReadExpr(f, dv, typeName);

    private sealed record Field(
        string Param, string ClrTypeFqn, string Key,
        TypeAnalysis.Wrap Wrap, TypeAnalysis.Scalar Scalar, string Inner);

    private sealed record Model(string Fqn, string TypeName, bool Valid, ImmutableArray<Field> Fields)
    {
        public string Safe { get; init; } = string.Empty;
    }
}
